CUDNN:
  BENCHMARK: false
  DETERMINISTIC: false
  ENABLED: true
BACKBONE_MODEL: 'pose_resnet'
MODEL: 'multi_person_posenet'
DATA_DIR: ''
GPUS: '0'
OUTPUT_DIR: './results/4D-OR-with-predictions/'
LOG_DIR: './results/4D-OR-with-predictions-log//'
WORKERS: 2
PRINT_FREQ: 100
WITH_SSV: false

DATASET:
  COLOR_RGB: True
  TRAIN_DATASET: 'fdor_with_predictions'
  TEST_DATASET: 'fdor_with_predictions'
  DATA_FORMAT: jpg
  DATA_AUGMENTATION: False
  SUFFIX: "pseudo_hrnet_soft_9videos"
  FLIP: False
  ROOT: 'data/4D-OR/data/' # 'data/panoptic/'
  ROT_FACTOR: 45
  SCALE_FACTOR: 0.35
  TEST_SUBSET: 'validation'
  TRAIN_SUBSET: 'train'
  ROOTIDX: 2
  CAMERA_NUM: 6
NETWORK:
  PRETRAINED_BACKBONE: ""
  PRETRAINED:  ""#"./models/pose_resnet_50_384x288.pth"
  TARGET_TYPE: gaussian
  TRAIN_BACKBONE: True
  TRAIN_ONLY_2D: True
  IMAGE_SIZE:
  - 2048
  - 1536
  HEATMAP_SIZE:
  - 512
  - 384
  SIGMA: 3
  NUM_JOINTS: 15
  USE_GT: False
POSE_RESNET:
  FINAL_CONV_KERNEL: 1
  DECONV_WITH_BIAS: False
  NUM_DECONV_LAYERS: 3
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_DECONV_KERNELS:
  - 4
  - 4
  - 4
  NUM_LAYERS: 50
LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  BATCH_SIZE: 1
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 20
  RESUME: true
  OPTIMIZER: adam
  LR: 0.0001
  LR_FACTOR: 0.1
  LR_STEP: [10, 15]
TEST:
  MODEL_FILE: 'model_best.pth.tar'
  BATCH_SIZE: 1
DEBUG:
  DEBUG: true
  SAVE_HEATMAPS_GT: true
  SAVE_HEATMAPS_PRED: true
MULTI_PERSON:
  SPACE_SIZE:
    - 8000.0
    - 8000.0
    - 2000.0
  SPACE_CENTER:
    - 0.0 # 120.0
    - -500.0 # -600.0
    - 800.0
  INITIAL_CUBE_SIZE:
    - 80
    - 80
    - 20
  MAX_PEOPLE_NUM: 10
  THRESHOLD: 0.3
PICT_STRUCT:
  GRID_SIZE:
    - 2000.0
    - 2000.0
    - 2000.0
  CUBE_SIZE:
    - 64
    - 64
    - 64
