CUDNN:
  BENCHMARK: false
  DETERMINISTIC: false
  ENABLED: true
BACKBONE_MODEL: "pose_resnet"
MODEL: "multi_person_posenet_ssv"
DATA_DIR: ""
GPUS: "0"
OUTPUT_DIR: "./results/4D-OR-voxelpose/"
LOG_DIR: "./results/4D-OR-voxelpose-log/"
WORKERS: 2
PRINT_FREQ: 100
WITH_SSV: True
WITH_ATTN: True
ATTN_WEIGHT: 0.1
ATTN_NUM_LAYERS: 18
USE_L1: True
L1_WEIGHT: 0.01
L1_ATTN: True

DATASET:
  COLOR_RGB: True
  TRAIN_DATASET: "voxelpose_fdor_ssv"
  TEST_DATASET: "voxelpose_fdor"
  DATA_FORMAT: jpg
  DATA_AUGMENTATION: False
  SUFFIX: "pseudo_hrnet_soft_9videos"
  FLIP: False
  ROOT: "data/4D-OR/data/" # 'data/panoptic/'
  ROT_FACTOR1: 45
  ROT_FACTOR2: 45
  SCALE_FACTOR1: 0.35
  SCALE_FACTOR2: 0.35
  APPLY_CUTOUT: True
  #APPLY_CUTOUT: False
  APPLY_RANDAUG: True
  #APPLY_RANDAUG: False
  TEST_SUBSET: "validation"
  TRAIN_SUBSET: "train"
  ROOTIDX:
    - 4
    - 5
  CAMERA_NUM: 6
  CAMERAS:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
NETWORK:
  PRETRAINED_BACKBONE: "models/4D-OR-voxelpose/backbone_final_with_project_pose.pth.tar"
  PRETRAINED: "" # 'models/pytorch/imagenet/resnet50-19c8e357.pth'
  TARGET_TYPE: gaussian
  INIT_ROOTNET: "models/4D-OR-voxelpose/rootnet_final_with_affine_transformation-and-pseudoroot-idx-and-slower-longer-training.pth.tar" #"models/cam5_rootnet_epoch2.pth.tar"
  INIT_ALL: ""
  TRAIN_BACKBONE: True
  TRAIN_ONLY_ROOTNET: False
  ROOTNET_TRAIN_SYNTH: True
  FREEZE_ROOTNET: True
  PRETRAINED_BACKBONE_PSEUDOGT: True
  ROOTNET_BUFFER_SIZE: 10000
  IMAGE_SIZE_ORIG:
    - 2048
    - 1536
  IMAGE_SIZE:
    - 960
    - 512
  HEATMAP_SIZE:
    - 240
    - 128
  SIGMA: 3
  NUM_JOINTS: 14
  USE_GT: False
  ROOTNET_ROOTHM: True
POSE_RESNET:
  FINAL_CONV_KERNEL: 1
  DECONV_WITH_BIAS: False
  #NUM_DECONV_LAYERS: 3
  NUM_DECONV_LAYERS: 3
  NUM_DECONV_FILTERS:
    - 256
    - 256
    - 256
  NUM_DECONV_KERNELS:
    #- 4
    - 4
    - 4
    - 4
  #NUM_LAYERS: 50
  NUM_LAYERS: 50
LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  BATCH_SIZE: 1
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 15 #8
  RESUME: false
  OPTIMIZER: adam
  LR: 0.00002 #0.0001
  LR_FACTOR: 0.1
  LR_STEP: [10, 13] #[5, 7]
  L1_EPOCH: 10
TEST:
  MODEL_FILE: "model_best.pth.tar"
  BATCH_SIZE: 1
DEBUG:
  DEBUG: true
  SAVE_HEATMAPS_GT: true
  SAVE_HEATMAPS_PRED: true
  SAVE_3D_POSES: true
  SAVE_3D_ROOTS: true
MULTI_PERSON:
  SPACE_SIZE:
    - 8000.0
    - 8000.0
    - 5000.0
  SPACE_CENTER:
    - 296.1
    - 826.0
    - -190.4
  INITIAL_CUBE_SIZE:
    - 80
    - 80
    - 80
  MAX_PEOPLE_NUM: 8
  THRESHOLD: 0.2
PICT_STRUCT:
  GRID_SIZE:
    - 2000.0
    - 2000.0
    - 2000.0
  CUBE_SIZE:
    - 64
    - 64
    - 64
